name: CMake lint, build, test

on: [push, pull_request]

env:
  SERENITY_ROOT: ${{ github.workspace }}

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # Do we need to update the package cache first?
    # sudo apt-get update -qq

    - name: Purge interfering packages
      # Remove GCC 9 (installed by default)
      run: sudo apt-get purge -y gcc-9 g++-9 libstdc++-9-dev

    - name: Install dependencies
      # These packages are already part of the ubuntu-20.04 image:
      # clang-format-10 cmake gcc-10 g++-10 shellcheck libgmp-dev
      # These aren't:
      run: sudo apt-get install libstdc++-10-dev libmpfr-dev libmpc-dev
      # If we ever do any qemu-emulation on Github Actions, we should re-enable this:
      # e2fsprogs qemu-system-i386 qemu-utils

    - name: Use GCC 10 instead
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10

    - name: Check versions
      run: set +e; g++ --version; g++-10 --version; clang-format --version; clang-format-10 --version

    - name: Lint (Phase 1/2)
      run: ${{ github.workspace }}/Meta/lint-ci.sh

    - name: Restore caches
      uses: actions/cache@v2
      with:
        # TODO: ccache
        path: |
          ${{ github.workspace }}/Toolchain/Cache/
        key: ${{ runner.os }}-toolchain

    - name: List caches
      working-directory: ${{ runner.workspace }}
      run: bash -c 'pwd; echo "${{ github.workspace }}"; ls -al || true; ls -al Toolchain || true; ls -al Toolchain/Cache || true;'

    - name: Restore or regenerate Toolchain
      run: TRY_USE_LOCAL_TOOLCHAIN=y ${{ github.workspace }}/Toolchain/BuildIt.sh

    - name: Create Build Directory
      working-directory: ${{ runner.workspace }}
      run: pwd; mkdir -p Build; ls

    - name: Create Build Environment
      working-directory: ${{ runner.workspace }}/Build
      run: pwd; ls ..; cmake .. -DBUILD_LAGOM=1 -DALL_THE_DEBUG_MACROS=1

    - name: Build Serenity and Tests
      working-directory: ${{ runner.workspace }}/Build
      run: cmake --build . -j2

    - name: Lint (Phase 2/2)
      working-directory: ${{ github.workspace }}/Meta
      run: ./check-symbols.sh

    - name: Run CMake tests
      working-directory: ${{ github.workspace }}/Build
      run: CTEST_OUTPUT_ON_FAILURE=1 make test

    - name: Run JS tests
      working-directory: ${{ github.workspace }}/Meta/Lagom
      run: DISABLE_DBG_OUTPUT=1 ./test-js

    - name: Monitor disk usage
      working-directory: ${{ runner.workspace }}
      run: du -ch Toolchain/Cache/* ; du -sch /home/travis/.ccache/* || true

# TRAVIS CODE:
#notifications:
#  irc:
#    if: repo = SerenityOS/serenity
#    channels:
#      - "chat.freenode.net#serenityos"
#    template:
#      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#      - "Subject: %{commit_subject}"
#      - "Details: %{build_url}"
#(20:13:35) travis-ci: SerenityOS/serenity#9818 (master - cfce6b3 : Andreas Kling): The build passed.
#(20:13:35) travis-ci: Subject: LibVT: Copying from terminal scrollback resulted in wrong text
#(20:13:35) travis-ci: Details: https://travis-ci.com/SerenityOS/serenity/builds/198023549

    # https://github.com/rectalogic/notify-irc
    - name: IRC result notification (direct push)
      uses: rectalogic/notify-irc@v1
      if: github.repository == 'BenWiederhake/serenity' && github.event_name == 'push' && !cancelled()
      with:
        channel: "#irc-ga-test"
        nickname: serenity-ga
        message: |
          ${{ github.actor }} pushed ${{ github.ref }} ${{ github.event.compare }}: ${{ job.status }}
          Commits: ${{ join(github.event.commits.*.message) }}
          Details: https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}

    - name: IRC result notification (PR)
      uses: rectalogic/notify-irc@v1
      if: github.event_name == 'pull_request' && !cancelled()
      with:
        channel: "#irc-ga-test"
        nickname: serenity-ga
        message: |
          ${{ github.actor }} opened PR ${{ github.event.html_url }}
